#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      web-search.sh
#   created:   24.02.2017.-08:59:54
#   revision:  ---
#   version:   1.0
# -----------------------------------------------------------------------------
# Requirements:
#   rofi
# Description:
#   Use rofi to search the web.
# Usage:
#   web-search.sh
# -----------------------------------------------------------------------------
# Script:

declare -A URLS

URLS=(
  ["duckduckgo"]="https://www.duckduckgo.com/?q="
  ["yandex"]="https://yandex.ru/yandsearch?text="
  ["github"]="https://github.com/search?q="
  ["stackoverflow"]="http://stackoverflow.com/search?q="
  ["symbolhound"]="http://symbolhound.com/?q="
  ["searchcode"]="https://searchcode.com/?q="
  ["openhub"]="https://www.openhub.net/p?ref=homepage&query="
  ["superuser"]="http://superuser.com/search?q="
  ["askubuntu"]="http://askubuntu.com/search?q="
  ["imdb"]="http://www.imdb.com/find?ref_=nv_sr_fn&q="
  ["rottentomatoes"]="https://www.rottentomatoes.com/search/?search="
  ["piratebay"]="https://thepiratebay.org/search/"
  ["youtube"]="https://www.youtube.com/results?search_query="
  ["vimawesome"]="http://vimawesome.com/?q="
  ["wikipedia"]="https://en.wikipedia.org/wiki/Special:Search?search="
)

# List for rofi
gen_list() {
  for i in "${!URLS[@]}"; do
    echo -en "$i\0info\x1f$i\n"
  done
}
global tester
main() {
  # Pass the list to rofi
  platform=$1
  query=$2
  if [[ "$ROFI_RETV" == 1 ]]; then
    tester=$1
  fi
  if [[ -n "$platform" ]]; then
    echo -en "\0prompt\x1f$platform\n\0meta\x1f$platform\n\0info\x1f$platform\nplat$platform inf$ROFI_INFO retv$ROFI_RETV @$@ tester$tester"
    if [[ -n "$query" ]]; then
      url=${URLS[$platform]}$query
      xdg-open "$url"
    else
      exit
    fi

  else
    gen_list
  fi
}

main "$1" "$2"

exit 0
